== HellOS 手记

都说编译器、操作系统和图形学是程序员的三大浪漫，我也不例外。很惭愧，在这三个领域我都有尝试过但却都是浅尝辄止。HellOS 便是我为了学习操作系统而发起的又一次尝试。但是，不同以往的是，这回我好像看到了一点曙光。

对于计算机编程，我一直相信动手实践是最好的学习方式。与其花大半年啃一本“深入浅出操作系统”然后又忘掉大部分内容，不如直接上手写一个，边写边学。市面上有不少关于操作系统的书，但大多是纯理论分析。理论固然是重要的，但没有在实践的经验的情况下，阅读一本纯理论的书并且理解它，是一件很不容易的事情。相信有很多朋友买了书后会有长期不开封，或者长期反复阅读第一章的体会。市面上也有一些实践的书，但往往会基于一定的基础。它们很可能没来由的开篇便具备了一个小型 Linux 内核，然后基于这个内核来讲解一些操作系统的概念和技术。对于初学者来说，这样的书籍也可能会让人望而却步，毕竟 Linux 内核的完成度已经很高了。但本项目并没有这样的原始基础，而是完全从零开始。虽然最终的规模不大、完成度也不高，但它涵盖了操作系统的许多核心概念和技术，也解开了计算机启动初期的神秘面纱。犹如每个新生命的诞生过程体现着生命演化的历史，计算机的启动过程也体现着当年计算机从无到有、CPU从雏形到完善的历史。这种跨纪元的年代感，也将是你我坚持下去的动力之一。

我为本项目制定了一个长期、完整而具有渐进性的路线图，大的节点有：BootLoader、16位实模式内核、16位保护模式内核、32位保护模式内核、64位长模式内核。我在过程中按照路线图一步一步实现。中间遇到难题可能磕磕碰碰止步几个月，解决了以后又较为迅速的进行了下去。

基于项目有较大概率会坚持到底达成既有目的的信心，我觉得有必要在项目过程中就把一些想法和经验记录下来，既是为了给自己一个总结，也希望能对后来者有所帮助。如果等项目完成后再写，那可能就失去了当下的很多感同身受的东西，丢了那么点“灵魂”性。

我会假定本手记的读者，也就是您，已经具备一定的计算机编程基础并熟悉C语言，也接触过一些汇编，哪怕只是大学课堂上学过一点、现在忘得差不多了也行。对计算机体系结构有基本概念即可，不需要精通。我对这些知识、原理不会有过多的、系统地阐述，但偶尔可能会有必要的简单解释。如果您对这些还不太熟悉，那么在阅读本手记的过程中可能会有些吃力，您可以先去补充一下相关的知识。

编写操作系统是一个非常有趣的过程，虽然可能会遇到很多挑战和困难，但每当你成功地实现一个功能或者解决一个问题时，那种成就感是无与伦比的。希望我的这篇手记能够激励更多的人去尝试编写自己的操作系统，体验这个充满乐趣的过程。

最后，我想说，很多年前大家都有很严重的拿来主义习惯，一旦有人在做重复的事情，会说：“嗨！你又造轮子了！”但其实，学习过程并不是造轮子，而是通过实践来理解。在当下的世界格局，拿来主义可能并不总是行得通了，尤其是在一些核心技术领域。我们需要更多的人去造轮子，去理解轮子的原理和设计，这样才能真正掌握技术的核心，推动技术的发展。而我这个 HellOS，就是星星之火，我希望更多的人能够去写操作系统，去写编译器，去写图形系统，去造各种轮子。我相信，HellOS 这颗星星之火，也能照亮一些人前行的路。

二零二六年五月
